### PR TITLE
Add fhardened

### PR DESCRIPTION
**Pull request by eslerm**
```
Currently, -fhardened enables:

  -D_FORTIFY_SOURCE=3 (or =2 for older glibcs)
  -D_GLIBCXX_ASSERTIONS
  -ftrivial-auto-var-init=pattern
  -fPIE  -pie  -Wl,-z,relro,-z,now
  -fstack-protector-strong
  -fstack-clash-protection
  -fcf-protection=full (x86 GNU/Linux only)
```

See [[PATCH] gcc: Introduce -fhardened](https://gcc.gnu.org/pipermail/gcc-patches/2023-September/630550.html) and the [GCC docs on -fhardened](https://gcc.gnu.org/onlinedocs/gcc/Instrumentation-Options.html#index-fhardened).

I added this to the top of the list, since it enables so many other flags and because it helps distros work together on hardening.

From an ecosystem and distro perspective, `-fhardened` is a very nice way to implement gcc compiler flags. Since the GCC project maintains these flags, distros will inherit new flags as they are added. This circumvents the security vs performance debate each distro internally has each time they add a new flag. When a distro adopts a new hardening flag, there will likely be packages which fail to build from source (often bugs in the package). The first distro to rebuild their archive with a new flag pays the highest cost, since most of the bugs have not been discovered or discussed yet. Being first to market has a high cost and slows down hardening adoption. Major distros can share this burden by using `-fhardened`, so that they inherit flags and begin finding bugs at roughly the same time.

### CODE REVIEW

**Comment by kpcyrd** [comment]
Could one argue that, if a distro has all of these options set manually, they qualify for this checkbox (until the definition of `-fhardened` is changed?)

**Comment by eslerm** [comment]
Could it be `equivalent` instead of `yes` or `no`?

Debian and Ubuntu do not use equivalent flags. From their wiki, Fedora seems to use all except `ftrivial-auto-var-init=pattern`. Same for Gentoo Hardened.

**Comment by kpcyrd** [comment]
I spent a lot of time on the recent `-D_FORTIFY_SOURCE=3` rollout in Arch Linux, the problem is that gcc docs make it sound like this only depends on glibc, but it's more a matter of "does this specific application depend on undefined behavior". Some C programmers tried to be extra-smart and used `malloc_usable_size` to access allocator internals for things that weren't meant to be.

For those specific packages we change the build flags back to `-D_FORTIFY_SOURCE=2`, but `-fhardened` would make this more complicated.

**Comment by eslerm** [comment]
Is that extra-smart `malloc_usable_size` kludge by systemd :D ? [I believe they are the only one doing that.](https://bugs.launchpad.net/ubuntu/+source/gcc-13/+bug/2012440/comments/1)

If you specify `-D_FORTIFY_SOURCE=2 -fhardened` or `-fhardened -D_FORTIFY_SOURCE=2` the compiler will drop `3` from `-fhardened`. (Marek gives a better example in [[PATCH] gcc: Introduce -fhardened](https://gcc.gnu.org/pipermail/gcc-patches/2023-September/630550.html).)

Thanks for merging \o/

**Comment by kpcyrd** [comment]
systemd was fixed in https://github.com/systemd/systemd/pull/25688, but that specific pattern has been present in quite a few projects, yes.

**Pull request merged**
